title: Adam Greenberg
author: Adam Greenberg
email: blog@edits.AdamGreenberg.com
description: > # this means to ignore newlines until "twitter_username:"
  Adam's Edits | Helping You Write Well

permalink: /:year/:month/:day/:title/

# social links
github_username:  AdamGreenberg
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

header_pages:
  - about.md
  - blog.md
  - adams-edits.md

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%a. %b, %d %Y" #formerly %b %-d, %Y

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-archives
 - jekyll-redirect-from

hidden_tags:
  - internal
  - draft
  - intern
  - interns
  - desk
  - drink
  - fun
  - office
  - podcast
  - podcasts
  - speed
  - copy machine
  - free
  - beverage
  - TOMS Shoes
  - Sapporo

hidden_categories:
  - internal
  - draft

jekyll-archives:
  enabled:
    - dates
    - categories
    - tags
  layouts:
    dates: archive-date
    categories: archive-category
    tags: archive-tag
  permalinks:
    dates: '/blog/:year/:month/:day/'
    categories: '/blog/category/:name/'
    tags: '/blog/tag/:name/'